Inventory/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from inventaire import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^inventaire/', include('inventaire.urls', namespace='inventaire')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

inventaire/urls.py
from django.conf.urls import url
from . import views  # import views so we can use them in urls.

app_name = 'inventaire'
urlpatterns = [
    url(r'^$', views.couverture, name='couverture'),
    url(r'^table/$', views.table, name='table'),
    url(r'^ajouter/$', views.ajouter, name='ajouter'),
]

inventaire/models.py
from django.db import models


# Create your models here.
class Expiration(models.Model):
    date = models.DateField()

    def __str__(self):
        return self.date.isoformat()


class GTIN(models.Model):
    numero = models.CharField(max_length=14)
    date_expiration = models.OneToOneField(Expiration, on_delete=models.CASCADE)

    def __str__(self):
        return self.date_expiration

inventaire/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Expiration, GTIN
from django.template import loader
from .form import ContactForm


# Create your views here.

def index(request):
    gtins = GTIN.objects.all().order_by('date_expiration')
    context = {
        'gtins': gtins
    }
    return render(request, 'inventaire/index.html', context)


def couverture(request):
    return render(request, 'inventaire/couverture.html')


def table(request):
    gtins = GTIN.objects.all().order_by('date_expiration')
    context = {
        'gtins': gtins
    }
    return render(request, 'inventaire/table.html', context)


def ajouter(request):
    gtins = GTIN.objects.all().order_by('date_expiration')
    context = {
        'gtins': gtins
    }
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            gtin = form.cleaned_data['gtin']
            date = form.cleaned_data['date']

            produit = GTIN.objects.filter(numero=gtin)
            if not produit.exists():
                                        produit = GTIN.objects.create(
                                        numero=gtin,
                                        date_expiration=date
                                        )
            else:
                                        produit.date_expiration = date

            return render(request, 'inventaire/Validation.html', context)
        else:
                context['errors'] = form.errors.items()
    else:
                                    form = ContactForm()
    context['form'] = form

    return render(request, 'inventaire/ajouter.html', context)

inventaire/templates/inventaire/Ajouter.html
{% extends 'inventaire/base.html' %}
 {% block content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
           role="button" aria-expanded="true" aria-controls="collapseCardExample">
            <h6 class="m-0 font-weight-bold text-primary">Ajouter ou Modifier un produit</h6>
        </a>
        <!-- Card Content - Collapse -->
        <div class="collapse show" id="collapseCardExample">
            <div class="card-body">
                <form class="form-inline" action="{% url 'inventaire:ajouter'%}" method="post">
                     {% csrf_token %}
                <div class="form-group">
                    <label for="name" class="control-label">GTIN</label>
                    <input type="text" name="name" value="" id="GTIN">
                </div>
                <div class="form-group">
                    <label for="date" class="control-label">Date</label>
                    <input type="date" name="date" value="" id="date">
                </div>
                <button type="submit" class="btn btn-success">Valider</button>
                </form>
            </div>
        </div>
    </div>
 {% endblock %}

inventaire/templates/inventaire/Couverture.html
{% extends 'inventaire/base.html' %}
 {% block content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
           role="button" aria-expanded="true" aria-controls="collapseCardExample">
            <h6 class="m-0 font-weight-bold text-primary">Liste des Produits</h6>
        </a>
        <!-- Card Content - Collapse -->
        <div class="collapse show" id="collapseCardExample">
            <div class="card-body">
                <li>Bienvenue</li>
            </div>
        </div>
    </div>
 {% endblock %}

inventaire/templates/inventaire/Validation.html
{% extends 'inventaire/base.html' %}

{% block content %}
    <hr>
    <h1 class="intro-text text-center">Merci !</h1>
    <hr class="detail-separator">
    <p>Votre produit est entrée dans la base de données</p>
    <hr>
{% endblock %}

inventaire/templates/inventaire/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>
    {% load static %}
    <!-- Custom fonts for this template-->
    <link href="{% static 'inventaire/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'inventaire/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>
<body>
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'inventaire:couverture' %}">
            <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">CB+</div>
        </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <li class="nav-item">
                    <a class="nav-link" href="{% url 'inventaire:ajouter' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Ajouter ou Modifier </span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inventaire:table' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
    <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                    <!-- Topbar Search -->
                 <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                            aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                 </form>
                </nav>
                {% block content %}{% endblock %}
            </div>
    </div>
</div>

<footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
<script src="{% static 'inventaire/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'inventaire/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'inventaire/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'inventaire/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'inventaire/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'inventaire/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'inventaire/js/demo/chart-pie-demo.js' %}"></script>
</body>
</html>

inventaire/templates/inventaire/index.html
{% extends 'inventaire/base.html' %}
{% block content %}
    {% include 'inventaire/list.html' %}
{% endblock %}

inventaire/templates/inventaire/list.html
<ul>
<li>Liste des Produits :</li>
{% for gtin in gtins %}
    <li>{{ gtin.numero}}     {{ gtin.date_expiration }}</li>
{% endfor %}
</ul>

inventaire/templates/inventaire/table.html
 {% extends 'inventaire/base.html' %}
 {% block content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
           role="button" aria-expanded="true" aria-controls="collapseCardExample">
            <h6 class="m-0 font-weight-bold text-primary">Liste des Produits</h6>
        </a>
        <!-- Card Content - Collapse -->
        <div class="collapse show" id="collapseCardExample">
            <div class="card-body">
                {% include 'inventaire/list.html' %}
            </div>
        </div>
    </div>
 {% endblock %}